"""empty message

Revision ID: 3dc6dcd3bf9d
Revises: 20c59ce10cf5
Create Date: 2020-05-12 11:06:35.555214

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3dc6dcd3bf9d'
down_revision = '20c59ce10cf5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_post_body', table_name='post')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_post_body', 'post', ['body'], unique=1)
    # ### end Alembic commands ###
